[package]
name = "jetty_sql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.64"
sqlparser = "0.22.0"

[dev-dependencies]
jetty_core = { path = "../jetty_core" }
