name: Rust

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        concurrency:
            group: ${{ github.ref }}
            cancel-in-progress: true

        runs-on: [self-hosted, macos]
        # runs-on: ubuntu-latest
        strategy:
            matrix:
                toolchain:
                    - stable

        steps:
            - uses: actions/checkout@v3
            - name: Set toolchain
              run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
            - name: Set up cargo cache
              uses: actions/cache@v3
              continue-on-error: false
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                  restore-keys: ${{ runner.os }}-cargo-
            - name: Check
              run: cd rusty_jetty && cargo check --verbose
            - name: Run unit tests
              run: cd rusty_jetty && cargo test --verbose --lib
            - name: Run doctests
              run: cd rusty_jetty && cargo test --verbose --doc
